version: "2"
services:
  leandrodasilva.dev:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm start"
    restart: always
